### PR TITLE
Fix Serilog input tests

### PR DESCRIPTION
**Pull request by karolz-ms**

### CODE REVIEW

**Comment by karolz-ms** [comment]
Hey @nblumhardt you did not run the tests before submitting https://github.com/Azure/diagnostics-eventflow/pull/64! :-)

No worries though, we've got your back

**Comment by nblumhardt** [comment]
Hey, thanks @karolz-ms! :-) ... I thought I did run `./tools/runtest.cmd` - did I miss a failure in the output somewhere there? (I might also have done the classic forget-to-save-in-VS-before-running-tests-from-the-cmdline..)

No CI server for this repo yet?

**Comment by karolz-ms** [comment]
Yes, `./tools/runtest.cmd` should have caught this. We do have a CI system in place for this repo and this script is what caught the problem... but the output is not public right now. Do you have any favorite CI system that you'd recommend for EventFlow?

**Comment by nblumhardt** [comment]
I've had a good experience with AppVeyor - though for Serilog we've ended up with both AppVeyor (Windows builds) and Travis CI (Linux/macOS).

**Pull request merged**
