### PR TITLE
Add net47 target framework

### PR DESCRIPTION
**Pull request by ghelyar**
Add a net47 target that uses the same package versions as the netstandard2.0 target. #261

### CODE REVIEW

**Comment by karolz-ms** [comment]
Thank you for the addition @ghelyar , much appreciated!

A few questions and suggestions:
1. Are you sure you do not want to have some of the inputs or outputs target net47 as well?
1. The [unit tests](https://github.com/Azure/diagnostics-eventflow/tree/master/test) should also have a run that targets net47... at least the Core assembly. It would also be nice to make a note in the [contribution guide](https://github.com/Azure/diagnostics-eventflow/blob/master/contributing.md) that .NET 4.7 SDK (targeting pack) is now required (and .NET Core 1.1 and 2.0 SDKs as well).
1. You will also need to modify the [assembly signing project](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Signing/Microsoft.Diagnostics.EventFlow.Signing.csproj) to account for new assemblies being built. So far we had 3 groups of assemblies there: "full", netstandard1.1 and netstandard2.0. This will no longer be sufficient, as we now have packages that have a binary for both net451 and net47 frameworks. I suggest creating a separate folder for assemblies targeting net47, e.g. named "full47". Let me know if you need help with this one.

**Comment by ghelyar** [comment]
Thanks for the feedback. I wasn't sure if e.g. the test project should have the targets updated as well. I'll update this on Tuesday 28.

**Comment by ghelyar** [comment]
After some further reading at https://github.com/dotnet/standard/issues/514 I'm thinking of bumping this up to net471. What do you think?

**Comment by karolz-ms** [comment]
Yes, I think targeting 4.7.1 makes a lot of sense. Thanks for your diligence, appreciate it!

**Pull request merged**
